services:
  owui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: owui
    ports:
      - "4401:4401"
    networks:
      - host
    environment:
      - PORT=4401
      - GLOBAL_LOG_LEVEL=DEBUG
    env_file:
      - owui.env
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    healthcheck:  # This section checks the container's health
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]  # Change the endpoint as needed
      interval: 30s  # Check every 30 seconds
      timeout: 10s  # Wait 10 seconds for the command to respond
      retries: 3     # Retry 3 times before marking as unhealthy
  #
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    volumes:
      - open-webui-pipelines:/app/pipelines
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  searxng:
    
    container_name: searxng
    image: searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"



volumes:
  open-webui: {}
  open-webui-pipelines: {}